// Content for the guides, FAQ and info pages. Plain data: build.mjs turns it into HTML.
// Inline markup: **bold** and [text](url). Keep facts sourced and dated.
// House style: no em dashes, en dashes or middle dots.

export const SITE = {
  name: "Glasto Quick Copy",
  tagline: "Glastonbury ticket day guides and a free group copy tool",
  adsenseClient: "ca-pub-2229524942259780",
  url: "https://glastobolt.co.uk", // the site's main address: canonical links and the sitemap use it
};

const UPDATED = "6 October 2026";
const ISO = "2026-10-06";

const OFFICIAL = {
  tickets: ["Glastonbury Festival: ticket information", "https://www.glastonburyfestivals.co.uk/information/tickets/"],
  register: ["See Tickets: Glastonbury registration", "https://glastonbury.seetickets.com/registration"],
  lookup: ["See Tickets: registration lookup", "https://glastonbury.seetickets.com/gfl/registration/lookup"],
  info: ["Glastonbury Festival: info hub", "https://www.glastonburyfestivals.co.uk/info/"],
  resale: ["Glastonbury Festival: ticket resale FAQ", "https://www.glastonburyfestivals.co.uk/news/2025-ticket-resale-faq/"],
  customer: ["See Tickets: Glastonbury customer service", "https://glastonbury.seetickets.com/customerservice"],
};

export const GUIDES = [
  {
    slug: "how-glastonbury-registration-works",
    title: "How Glastonbury registration works",
    summary: "Who needs to register, what you need, how long photo checks take and how to find your registration number again.",
    updated: UPDATED, isoDate: ISO,
    body: [
      "You can't buy a Glastonbury ticket for anyone who hasn't registered first. Registration links a photo to each person, and that photo is printed on their ticket. It's how the festival stops touts: tickets are non-transferable, and security checks that the person at the gate matches the photo.",
      { h2: "Who needs to register" },
      "Everyone who will be **13 or over on the day the gates open** needs a ticket, and so needs to be registered. Children aged 12 and under don't need a ticket and don't register.",
      "If you're buying for friends, each of them must have their own registration. On ticket day you'll need two things for every person: their **registration number** and the **postcode they registered with**.",
      { h2: "What you need to register" },
      { ul: [
        "A few basic contact details, including an email address you check.",
        "A recent, passport-style photo of your face: facing the camera, well lit, no sunglasses or hat, and only you in the picture.",
        "A few minutes. Registration is free and done on the official See Tickets registration page.",
      ] },
      { h2: "How long the photo check takes" },
      "After you submit, your photo is checked by hand. The festival says this happens **within about 48 hours in the working week**. If it's accepted, you get an email with your registration number and registered postcode.",
      "If your photo is rejected, you'll get an email telling you. If you haven't heard anything within a further 48 hours, the advice is to register again.",
      { tip: "Register weeks before the sale, not days. Registration is usually paused around ticket sales, and you may need time to resubmit a photo." },
      { h2: "Keeping your photo up to date" },
      "Your confirmation email includes links to view, edit or delete your registration and to update your photo. The festival encourages updating the photo every year so it still looks like you.",
      "You **can't change your photo while you have a booking linked to your registration**, so update it before ticket day if it's out of date. The official advice is to check your registration at least 7 days before registration closes.",
      { h2: "Lost your registration number?" },
      "Use the official **registration lookup** on See Tickets. Enter the email address you registered with and you'll be sent your registration number again, along with the links to manage your details.",
      { h2: "Getting your group's numbers together" },
      "Ask everyone in your group to send you their registration number and registered postcode well before the sale. Check each one against the confirmation email if you can: a single wrong digit means that person won't be added to your booking.",
      "Once you have them, you can put them all on one page with [Glasto Quick Copy](/#/new) and tap to copy each one on the day.",
      { cta: "Put your group on one page" },
    ],
    sources: [OFFICIAL.tickets, OFFICIAL.register, OFFICIAL.lookup],
  },
  {
    slug: "ticket-day-checklist",
    title: "Glastonbury ticket day checklist",
    summary: "What to sort out the week before, the night before and in the minutes before the sale opens, so nothing slows you down.",
    updated: UPDATED, isoDate: ISO,
    body: [
      "Glastonbury tickets usually sell out in under an hour. The queue is luck, but what happens after you get through isn't. This checklist covers the things you can control.",
      { h2: "A week or more before" },
      { ul: [
        "**Everyone is registered** with an accepted photo, and has their confirmation email.",
        "**You've collected every registration number and registered postcode** for your group, up to six people in one booking.",
        "**You've agreed who books.** One person, the lead booker, enters everyone's details and pays the deposits. Agree who pays back whom before the day.",
        "**The lead booker has a card ready** with enough available for a deposit per person.",
        "If your group is bigger than six, split into booking groups and agree who books for whom, so nobody is bought twice and nobody is missed.",
      ] },
      { h2: "The night before" },
      { ul: [
        "Charge your phone and laptop, and check your internet connection.",
        "Make sure the lead booker knows their own registration number: recent sales have asked for it before you can even join the queue.",
        "Put your group's numbers somewhere you can copy them from quickly. Scrolling a busy group chat costs time.",
        "Check the official Glastonbury news page for the exact sale time and any changes to the process.",
      ] },
      { h2: "In the 15 minutes before" },
      { ul: [
        "Be on the official See Tickets Glastonbury page a few minutes before the sale starts.",
        "Use one device and one browser tab for each registration number. In recent sales extra tabs and devices on the same registration didn't give you an extra place.",
        "Don't refresh once you're in the queue unless the official instructions tell you to.",
        "Keep your phone screen on so it doesn't lock while you wait.",
      ] },
      { h2: "When you get through" },
      { ol: [
        "Enter the lead booker's details, then each person's registration number and registered postcode.",
        "Check the names that appear match your group before you continue.",
        "Pay the deposits and wait for the confirmation page.",
        "Screenshot the confirmation and the order reference, and tell the group straight away so others can stop trying for the same people.",
      ] },
      { tip: "Copy each number with one tap instead of typing it. Typing six ten-digit numbers under pressure is where mistakes happen." },
      { cta: "Get your group ready now" },
    ],
    sources: [OFFICIAL.tickets, OFFICIAL.info],
  },
  {
    slug: "how-the-ticket-queue-works",
    title: "How the Glastonbury ticket queue works",
    summary: "What happens when the sale opens, why extra tabs no longer help, and what you can and can't control.",
    updated: UPDATED, isoDate: ISO,
    body: [
      "Demand for Glastonbury tickets is many times the number available, so the sale runs through an online waiting room. Here's how it has worked in recent years and what that means for you.",
      { h2: "Joining the queue" },
      "In the 2027 sale, buyers completed a captcha and then had to **enter a registration number before joining the queue**. Each person was given a unique queue ID linked to that registration.",
      "That change means opening more tabs, browsers or devices with the same registration number gives you the same place, not a second chance. Several people in your group can each try with their own registration number, though, and whoever gets through first books for everyone.",
      { h2: "While you wait" },
      { ul: [
        "Leave the page open and let it move on by itself.",
        "Don't refresh unless the official instructions say to. Refreshing can lose your place or trip the anti-bot checks.",
        "Keep the device awake and plugged in.",
        "Have your group's numbers ready to paste the moment you get through.",
      ] },
      { h2: "If someone in your group gets through" },
      "They should book for everyone they've agreed to cover, up to six people. As soon as the booking is confirmed, they should tell the group, so nobody else spends their turn booking the same people.",
      { h2: "If you don't get a ticket" },
      "There's usually a second chance in the spring resale, when tickets that weren't fully paid for are sold again. See [our resale guide](/guides/resale-and-coach-tickets/).",
      { tip: "The queue can't be beaten, but the minute after it can be slowed down by missing numbers. Have them ready." },
    ],
    sources: [OFFICIAL.tickets, OFFICIAL.info],
  },
  {
    slug: "buying-tickets-for-a-group",
    title: "Buying Glastonbury tickets for a group",
    summary: "How one lead booker buys for up to six people, what they need from everyone, and how bigger groups can split up.",
    updated: UPDATED, isoDate: ISO,
    body: [
      "Most people go to Glastonbury with friends, and the booking system is built for that. One person can buy tickets for a small group in one go, as long as they have everyone's details.",
      { h2: "Up to six people per booking" },
      "A lead booker can buy **up to six tickets in one transaction**: their own and up to five more. For each person they enter that person's **registration number** and **registered postcode**.",
      "The lead booker pays the deposit for everyone in the booking. Everyone in the booking must be registered with an accepted photo before the sale.",
      { h2: "What to collect from each friend" },
      { ul: [
        "Their registration number, copied from their confirmation email.",
        "The postcode they registered with. If they've moved since, it's still the registered postcode that matters, unless they've updated their registration.",
        "Confirmation that their photo was accepted.",
      ] },
      { h2: "Groups bigger than six" },
      "Split into booking groups of up to six and give each group more than one person who'll try in the queue. Write down who covers whom. When a booking goes through, cross those people off straight away so nobody is booked twice and nobody is forgotten.",
      { h2: "Sharing the numbers safely" },
      "Registration numbers and postcodes aren't passwords, but they are personal details. Share them only with your group, not in public posts. With [Glasto Quick Copy](/#/new) the lead booker can put everyone on one page and send the group a link that only contains first names, numbers and postcodes.",
      { h2: "Paying each other back" },
      "Agree before the day how deposits and balances will be split. A short message in the group chat with the amounts and dates saves awkward conversations later.",
      { cta: "Make your group's page" },
    ],
    sources: [OFFICIAL.tickets],
  },
  {
    slug: "deposits-and-balance-payments",
    title: "Glastonbury deposits and balance payments explained",
    summary: "Why you pay a deposit first, when the balance is due, and what happens if you can't pay or can't go.",
    updated: UPDATED, isoDate: ISO,
    body: [
      "Glastonbury general admission tickets are bought in two parts: a deposit when you book, and the balance in the spring. This spreads the cost, but it also means there's a deadline to remember.",
      { h2: "The deposit" },
      "When you book, the lead booker pays a deposit for each person in the booking. In the 2027 sale the deposit was **£100 per ticket**, on a ticket price of £408.",
      { h2: "The balance" },
      "The rest is paid during a set **balance payment window**, usually in the first week of April. Check the official balance payment guidance each year for exactly who can pay and how. The festival and See Tickets send reminders, but it's your responsibility to pay in time.",
      { tip: "Put the balance window in your calendar the day you book, with a reminder a few days before." },
      { h2: "If the balance isn't paid" },
      "If a balance isn't paid by the end of the window, that ticket is cancelled. In recent years the deposit was refunded minus an administration fee. Cancelled tickets go back on sale in the spring resale.",
      { h2: "If you can't go" },
      "Tickets can't be transferred to anyone else. For 2027 the festival said you could ask See Tickets for a refund until early May, minus a £25 administration fee per ticket, after which tickets become non-refundable.",
      { h2: "Extras" },
      "Car parking and other extras have been sold around the balance payment window in recent years. Check the official site for what's available each year.",
    ],
    sources: [OFFICIAL.tickets, OFFICIAL.customer],
  },
  {
    slug: "resale-and-coach-tickets",
    title: "Glastonbury resale and coach tickets",
    summary: "How the spring resale works, how coach packages differ from general admission, and how to prepare for both.",
    updated: UPDATED, isoDate: ISO,
    body: [
      "If you miss out in the main sale, it isn't necessarily over. And if you'd rather not drive, coach packages are a separate route in.",
      { h2: "Coach tickets" },
      "Ticket and coach packages combine a festival ticket with return coach travel from towns and cities around the UK. They're usually sold a few days before general admission tickets, in their own sale.",
      "Coach sales follow the same rules: everyone must be registered, and you need each person's registration number and registered postcode. Because coach seats are limited, the number of tickets per transaction can be lower than six: in the resale it has been limited to two.",
      { h2: "The spring resale" },
      "After the balance payment window closes, tickets that weren't paid for go back on sale in the **resale**, usually in April. In recent years there have been two resale sessions: one for ticket and coach packages, and one for general admission.",
      "The resale works like the main sale: online queue, registration numbers and postcodes, and a limited number of tickets. Resale tickets are usually paid in full at the time of booking rather than with a deposit.",
      { h2: "Avoid unofficial sellers" },
      "Glastonbury tickets carry the holder's photo and are strictly non-transferable. The official resale through See Tickets is the only legitimate way to get a returned ticket. Anyone selling tickets elsewhere is either mistaken or a scam.",
      { tip: "Keep your registration photo up to date between sales, so you're ready if a resale comes round." },
    ],
    sources: [OFFICIAL.resale, OFFICIAL.tickets],
  },
  {
    slug: "ticket-day-mistakes",
    title: "Common Glastonbury ticket day mistakes",
    summary: "The small slips that cost people tickets every year, and how to avoid each one.",
    updated: UPDATED, isoDate: ISO,
    body: [
      "Most ticket day disappointment is down to the queue. But every year some groups get through and still lose time or places to avoidable slips.",
      { h2: "1. Someone isn't registered" },
      "Or their photo was rejected and nobody noticed. Ask everyone to forward their confirmation email well before the day.",
      { h2: "2. The wrong postcode" },
      "The postcode must be the one the person registered with. If someone has moved, check which postcode their registration has.",
      { h2: "3. A typo in a registration number" },
      "Typing ten digits under time pressure is easy to get wrong. Copy and paste instead, and double check the names that appear before paying.",
      { h2: "4. Hunting through the group chat" },
      "Numbers scattered across weeks of messages are slow to find. Collect them in one place beforehand. [Glasto Quick Copy](/#/new) is built for exactly this.",
      { h2: "5. Two people booking the same friends" },
      "Agree who covers whom, and announce bookings the moment they're confirmed.",
      { h2: "6. Too many tabs" },
      "In recent sales, extra tabs and devices with the same registration number didn't help, and refreshing could lose your place.",
      { h2: "7. Forgetting the balance" },
      "Getting a deposit isn't the end. Put the balance payment dates in your calendar straight away.",
      { cta: "Get organised before the sale" },
    ],
    sources: [OFFICIAL.tickets],
  },
  {
    slug: "how-to-use-glasto-quick-copy",
    title: "How to use Glasto Quick Copy",
    summary: "A step-by-step guide to putting your group on one page, sharing it and using it on ticket day.",
    updated: UPDATED, isoDate: ISO,
    body: [
      "Glasto Quick Copy is a free tool that puts your whole group's registration numbers and postcodes on one page, so on ticket day you can tap to copy each one and paste it straight into the booking form.",
      { h2: "1. Paste your group chat" },
      "Open the tool and choose **Make your group's page**. Paste the messages where your friends sent their details. The tool picks out names, registration numbers and postcodes as you paste, and flags anyone whose postcode is missing.",
      "Prefer typing? Choose **Add someone by hand** and fill in each person.",
      { h2: "2. Check and save" },
      "Check each person's number against what they sent. When everyone shows as ready, create the group. It's saved in your browser on your phone. There's no account to make.",
      { h2: "3. Send everyone the link" },
      "Use **Share link** or **Copy link** to send the page to your group. It opens the same page on their phones, ready to use, and they can save it too. The link contains first names, registration numbers and postcodes only, so keep it within the group.",
      { h2: "4. On ticket day" },
      "When you get through the queue, open your group. Tap a box to copy it, paste it into the booking form, and move on. The next box to copy is highlighted, a progress bar counts what's done, and you can turn on **Keep screen on** so your phone doesn't lock.",
      { h2: "Privacy" },
      "The tool runs in your browser. Your group is saved on your phone only, and the tool's code never sends it anywhere. The site is free because it shows Google ads, so Google's ad code also runs on these pages. The code is open source, and a public check compares the live site with the published code every six hours.",
      { cta: "Open the tool" },
    ],
  },
];

const FAQ_ITEMS = [
  ["What is Glasto Quick Copy?", "A free, unofficial helper for Glastonbury ticket day. It puts your group's registration numbers and postcodes on one page so you can copy each one with a tap instead of typing or scrolling through messages."],
  ["Is this the official Glastonbury website?", "No. We're an independent project, not connected to Glastonbury Festival or See Tickets. You still register and buy tickets on the official sites."],
  ["Does it get me tickets faster?", "It can't speed up the queue. It saves time once you're through, when you need to enter up to six registration numbers and postcodes quickly and accurately."],
  ["Is it free?", "Yes. The tool and guides are free, paid for by ads from Google."],
  ["Where are my group's details stored?", "In your browser's storage on your own device. The tool has no accounts and no database, and its code never sends your group's details anywhere. Like any site with ads, Google's ad code runs on these pages. See our [privacy and cookies policy](/privacy/)."],
  ["Can other people see my group's numbers?", "Only people you send the share link to. The link contains first names, registration numbers and postcodes, and anyone with the link can read them, so share it only with your group."],
  ["How many people can I add?", "Up to six, the maximum one lead booker can buy for in a single Glastonbury booking."],
  ["Who needs to register for Glastonbury?", "Everyone who will be 13 or over when the gates open. Children aged 12 and under don't need a ticket or a registration. See [how registration works](/guides/how-glastonbury-registration-works/)."],
  ["What do I need for each person on ticket day?", "Their registration number and the postcode they registered with."],
  ["I've lost my registration number. What now?", "Use the official registration lookup on See Tickets with the email address you registered with, and your number will be emailed to you again."],
  ["How long does photo approval take?", "The festival says photos are reviewed within about 48 hours in the working week. If you hear nothing within a further 48 hours, register again."],
  ["Can I change my registration photo after booking?", "Not while a booking is linked to your registration, so update an old photo before ticket day."],
  ["Do extra tabs or devices help in the queue?", "In recent sales, no. You entered a registration number before queueing and received one queue ID linked to it, so extra tabs on the same registration gave the same place. See [how the queue works](/guides/how-the-ticket-queue-works/)."],
  ["How much is the deposit?", "In the 2027 sale it was £100 per ticket, with the balance due in a payment window in early April. See [deposits and balances](/guides/deposits-and-balance-payments/)."],
  ["What if someone in my group can't pay the balance?", "If the balance isn't paid by the end of the window, that ticket is cancelled and goes into the spring resale. In recent years the deposit was refunded minus an admin fee."],
  ["Can I give my ticket to a friend?", "No. Glastonbury tickets carry the holder's photo and are non-transferable. Returned tickets are sold again only through the official resale."],
  ["Is there a resale?", "Usually, in the spring, for tickets that weren't fully paid for. See [resale and coach tickets](/guides/resale-and-coach-tickets/)."],
  ["Does the tool work on iPhone and Android?", "Yes, in any modern browser. Copying uses your browser's clipboard. If copying fails, you can press and hold to select the number instead."],
  ["What does Keep screen on do?", "It asks your browser to stop the screen locking while your group's page is open, if your browser supports it. It switches off when you leave the page."],
  ["How do I delete my data?", "In the tool, open How your data is handled and choose Delete everything on this phone. Clearing your browser's site data also removes it."],
  ["Who makes this?", "A product manager, not a professional developer, who got fed up scrolling the group chat for numbers every ticket day. See [About](/about/)."],
];

export const PAGES = [
  {
    file: "guides/index.html", path: "/guides/", title: "Glastonbury ticket guides",
    description: "Guides to Glastonbury registration, ticket day, the online queue, buying for a group, deposits, balance payments, resale and coach tickets.",
    lead: "Everything you need to know before, during and after the Glastonbury ticket sale. Checked against official sources.",
    body: [{ cards: GUIDES }, { cta: "Make your group's page" }, { ad: "guides-end" }],
  },
  {
    file: "faq/index.html", path: "/faq/", title: "Frequently asked questions",
    description: "Answers about Glastonbury registration, the ticket queue, deposits and resale, and how Glasto Quick Copy works and keeps your details private.",
    lead: "Quick answers about Glastonbury tickets and about this site.",
    updated: UPDATED,
    faqSchema: FAQ_ITEMS,
    body: [
      { faq: FAQ_ITEMS.slice(0, Math.ceil(FAQ_ITEMS.length / 2)) },
      { ad: "faq-mid" },
      { faq: FAQ_ITEMS.slice(Math.ceil(FAQ_ITEMS.length / 2)) },
      { cta: "Try the tool" },
      { ad: "faq-end" },
    ],
  },
  {
    file: "about/index.html", path: "/about/", title: "About Glasto Quick Copy",
    description: "Who makes Glasto Quick Copy, why it exists, how the guides are checked and how the site is funded.",
    body: [
      "Glasto Quick Copy is an independent, free project. It's made by a product manager, not a professional developer, who got fed up scrolling the group chat for six registration numbers every Glastonbury ticket day.",
      { h2: "What we do" },
      { ul: [
        "**A free tool** that puts your group's registration numbers and postcodes on one page, so you can copy each one with a tap.",
        "**Guides** that explain registration, the ticket queue, deposits, balances and resale in plain English.",
      ] },
      { h2: "How the guides are checked" },
      "Every guide is based on the official Glastonbury Festival and See Tickets information, which we link to at the end of each article. Each page shows when it was last checked. Rules can change from year to year, so the official sites always have the final word. If you spot something out of date, [tell us](/contact/) and we'll fix it.",
      { h2: "How it's built" },
      "The tool's code is open source on [GitHub](https://github.com/francproductmanager/glastonbury-registration-quick-copy), built with the help of AI coding tools and tested automatically on every change. A public check compares the live tool with the published code every six hours.",
      { h2: "How it's funded" },
      "The site shows ads from Google AdSense, which pay for the domain and keep everything free. Ads sit in a few fixed places on each page, never between the copy buttons you use on ticket day. See our [privacy and cookies policy](/privacy/).",
      { h2: "Not affiliated" },
      "We're not affiliated with, endorsed by or connected to Glastonbury Festival or See Tickets. \"Glastonbury\" is used only to describe what the guides and tool are about.",
      { ad: "about-end" },
    ],
  },
  {
    file: "contact/index.html", path: "/contact/", title: "Contact",
    description: "How to contact Glasto Quick Copy about the guides, the tool, corrections, privacy or security.",
    body: [
      "We'd love to hear from you, whether it's a correction, an idea, a bug or a privacy question.",
      { h2: "Corrections, ideas and bugs" },
      "Open an issue on our public [GitHub page](https://github.com/francproductmanager/glastonbury-registration-quick-copy/issues/new/choose). Please don't include real registration numbers or postcodes.",
      { h2: "Security problems" },
      "Please report security issues privately through GitHub's [private vulnerability reporting](https://github.com/francproductmanager/glastonbury-registration-quick-copy/security/advisories/new) rather than in public.",
      { h2: "Privacy questions" },
      "For questions about your data or this site's cookies, see our [privacy and cookies policy](/privacy/), then contact us using the options above.",
      { h2: "Ticket questions" },
      "We can't help with bookings, refunds or registrations: we're not connected to the festival. Please contact [See Tickets customer service](https://glastonbury.seetickets.com/customerservice) or check the [official Glastonbury website](https://www.glastonburyfestivals.co.uk/information/tickets/).",
    ],
  },
  {
    file: "privacy/index.html", path: "/privacy/", title: "Privacy and cookies policy",
    description: "How Glasto Quick Copy handles your group's details and this site's data, including Google AdSense cookies and how to opt out.",
    updated: UPDATED,
    body: [
      "This policy explains what happens to your information on this site, including the Glasto Quick Copy tool. We've written it to be read, not skimmed past.",
      { h2: "Who we are" },
      "Glasto Quick Copy is an independent, free project run by an individual in the United Kingdom. You can reach us through the options on our [contact page](/contact/).",
      { h2: "The tool: your group's details stay on your device" },
      "The names, registration numbers and postcodes you add to the tool are saved only in your browser's storage on your device. The tool has no accounts and no database, and its own code never sends your group's details to us or anyone else.",
      "This site, including the tool's pages, shows Google ads. Google's ad code runs in your browser on these pages, as it does on any site with Google ads. It's Google's standard ad code and nothing else; we don't add other trackers or analytics.",
      "If you create a share link, the first names, registration numbers and postcodes are packed into the part of the link after the # symbol, which browsers don't send to web servers. Anyone you send the link to can read those details.",
      { h2: "The rest of this site" },
      "We don't ask you for any personal information on this site, and there are no accounts or forms.",
      { h3: "Hosting" },
      "This site is hosted by Netlify. Like any web host, Netlify processes technical information such as your IP address and browser details to deliver pages and protect the service. See [Netlify's privacy policy](https://www.netlify.com/privacy/).",
      { h3: "Advertising" },
      "This site uses Google AdSense to show ads. Third-party vendors, including Google, use cookies to serve ads based on your prior visits to this website or other websites. Google's use of advertising cookies enables it and its partners to serve ads to you based on your visits to this site and/or other sites on the internet.",
      "You can opt out of personalised advertising by visiting Google's [Ads Settings](https://adssettings.google.com/). You can also opt out of some third-party vendors' use of cookies for personalised advertising at [www.aboutads.info](https://www.aboutads.info/choices/) or, in the UK and Europe, [www.youronlinechoices.eu](https://www.youronlinechoices.eu/).",
      "Learn more about [how Google uses information from sites that use its services](https://policies.google.com/technologies/partner-sites) and about [Google's advertising technologies](https://policies.google.com/technologies/ads).",
      { h3: "Your consent" },
      "If you visit from the UK, the European Economic Area or Switzerland, a consent message from Google lets you choose whether to accept cookies for personalised ads before they're used. If you decline, Google may still show non-personalised ads, which use cookies for things like frequency capping and fraud prevention. You can change your choice at any time using the privacy and cookie settings link the message provides.",
      { h2: "Your rights" },
      "Under UK data protection law you have rights to access, correct and delete your personal data and to object to its use. Because we don't collect personal data ourselves, most requests will be about Google's advertising, which you can manage through the links above. You can also complain to the [Information Commissioner's Office](https://ico.org.uk/make-a-complaint/).",
      { h2: "Children" },
      "This site is not aimed at children under 13 and we don't knowingly collect their information.",
      { h2: "Changes" },
      "We'll update this page if anything changes and show the date it was last checked below.",
    ],
  },
  {
    file: "terms/index.html", path: "/terms/", title: "Terms of use",
    description: "The terms for using Glasto Quick Copy: the guides, the FAQ and the group copy tool.",
    updated: UPDATED,
    body: [
      "By using this site or the Glasto Quick Copy tool you agree to these terms. They're short.",
      { h2: "Not official" },
      "Glasto Quick Copy is independent and not affiliated with Glastonbury Festival or See Tickets. Tickets can only be bought through the official channels.",
      { h2: "Information, not advice" },
      "We work hard to keep the guides accurate and link to official sources, but ticket rules, dates and prices can change. Always check the official websites before acting. We can't accept responsibility for decisions made based on these guides.",
      { h2: "The tool" },
      "The tool is provided free and as is, without warranty. You're responsible for checking that the numbers and postcodes you add are correct, and for who you share your group's link with. We can't guarantee the tool will work on every device or browser, or on ticket day.",
      { h2: "Use it fairly" },
      "Don't use the site or tool for anything unlawful, to collect other people's details without their agreement, or to try to break the official ticket sale's rules.",
      { h2: "Open source" },
      "The tool's code is published under the [MIT licence](https://github.com/francproductmanager/glastonbury-registration-quick-copy/blob/main/LICENSE). The guides' text is not part of that licence.",
      { h2: "Law" },
      "These terms are governed by the law of England and Wales.",
    ],
  },
  {
    file: "404.html", path: "/404", title: "Page not found",
    description: "We couldn't find that page. Browse our Glastonbury ticket guides, the FAQ or the free group copy tool instead.",
    body: ["Sorry, we couldn't find that page. Try the [guides](/guides/), the [FAQ](/faq/) or the [home page](/)."],
  },
];
